seed: 2
num_envs: 1
batch_size: 32
discount: 0.99
learning_rate: 1e-3
train_episodes: 500
eval_episodes: 200
epsilon: 0.05
replay_capacity: 10000
min_replay_size: 100
sgd_period: 1 
target_update_period: 4 

save_dir: "./exp/${wandb.group}/${wandb.name}"
wandb:
  entity: "ucl-dark"
  project: ipd
  group: 'batched_catch'
  name: run-${seed}
  log: True

# layers: 
#   input_size: 1
#   layer1_size: 128
#   layer2_size: 128
#   output_size: 1 