seed: 0
num_batches: 75
batch_size: 16
learning_rate: 0.001
epochs: 50
discount: 0.5
epsilon: 0.1
replay_capacity: 1000

save_dir: "./exp/${wandb.group}/${wandb.name}"
wandb:
  entity: "ucl-dark"
  project: ipd
  group: 'catch_dqn'
  name: run-${seed}
  log: true

layers: 
  input_size: 1
  layer1_size: 128
  layer2_size: 128
  output_size: 1 